version: "3"

services:
  db:
    command: --default-authentication-plugin=mysql_native_password
    container_name: recipes-db
    environment:
      MYSQL_ROOT_PASSWORD: password
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    volumes:
      - data-volume:/var/lib/mysql
      - ./my.cnf:/etc/mysql/mysql.cnf
    command: mysqld --character-set-server=utf8mb4  --collation-server=utf8mb4_unicode_ci --skip-character-set-client-handshake
    
  migration:
    image: flyway/flyway
    depends_on:
      - db
    container_name: recipes-migration
    volumes:
      - ./database/schema:/flyway/sql

  api:
    build:
      context: ./backend
    command: reflex -r '\.go$$' -s -- sh -c 'go run cmd/api/main.go -databaseDatasource="${DATABASE_DATASOURCE}" -port=10001'
    container_name: recipes-api
    ports:
      - 10001:10001
    environment:
      - AWS_PROFILE=recipes
    volumes:
      - ./backend:/app
      - ~/.aws:/root/.aws:ro
    working_dir: /app

volumes:
  data-volume:
  careler_node_modules-volume:
